package Exception;

public class ExceptionDemo {
    public static void main(String[] args) throws ArithmeticException{
      /* try {
           System.out.println(10 / 0);
           System.out.println("Suresh");
           System.out.println("naresh");

       }catch(ArithmeticException ae){
           System.out.println("I am catch");
        }
           finally{
           System.out.println("I am from finally");
       }*/

        System.out.println(10 / 2);


       System.out.println("Venkatesh");
        System.out.println("naresh");
        System.out.println("prakash");



    }
}
